language:
- node_js
node_js:
- 14
services:
- mongodb
script:
- npm install
- npm install heroku
- npm install chai
- npm install chai-http
after_success:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cer1G976LoXPun48rNa/1/zTyC4CJI4VUFzVO2CAPENgiDmL3FkK04sLZDx+h1v6uqVscx1Gpb7YFOXXqOi3onJXUOCIpbdgxkKXXFsN19q0gHUUpeQron48eGPsva7Mup3XW7Xu6WjEt7b1wxBgwihhk7VXC5bYswNKJZHEVvRm20mndUV3tc80Va3zDBsYPYDDtbFAdUi1xBJiQ+Ru9ypNFdw/9DsZ3pqZ5ne9x49YRMyJNIuGmXFg+SeM9GiqxBXiD8pJ30v+SmTTC3/BGrg01S4uUjkk1ca+6KjtEecBjvci7yq12vKODeSSSjxiD9maNH1ce9pOb4YDkbMo3RNyM677GjrsRPbJ1oQgBDfGIWJLJjLJS4168hG8wN4PeuF5TbwuJz/d4UznSCUzeLvV64nGQ/dX2qToydDHPyuLsHw2wvm+i00OsSr3O0TKW/q4Id+Ot/WNvxoKUS6C3EKmoXdstA+6zpWh2meq7cb0wWh/P/HvM+Rt9ceCiocrkniFkZbZtBE5liZ1GVOrnX58Hd/ymVuNm8nZZNamMDplwOYcMzB1xEjUaRyG9Uvres12uXzrxhbClAHf/Ob2hnqodcAVlyNeEZRoubqxXiL2qVasdrkrcvk5biwm18PjSv06yF8rs4QDVhJsjVUdh8MN/A69To/9d2PJE9dnLaI=
  app: my-personal-network
  on:
    repo: cs130-w21/4
    branch: travis_doc
notifications:
  email:
    on_success: never
    on_failure: always
